#
# Module manifest for module 'Az'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/30/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.psm1'

# Version number of this module.
ModuleVersion = '14.3.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd48d710e-85cb-46a1-990f-22dae76f6b5f'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with PowerShell and Windows PowerShell.
For more information about the Az module, please visit the following: https://learn.microsoft.com/powershell/azure/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '5.2.0'; }, 
               @{ModuleName = 'Az.Advisor'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Aks'; RequiredVersion = '7.0.0'; }, 
               @{ModuleName = 'Az.AnalysisServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.ApiManagement'; RequiredVersion = '4.1.0'; }, 
               @{ModuleName = 'Az.App'; RequiredVersion = '2.0.1'; }, 
               @{ModuleName = 'Az.AppConfiguration'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ApplicationInsights'; RequiredVersion = '2.3.0'; }, 
               @{ModuleName = 'Az.ArcResourceBridge'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.ArizeAI'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.Attestation'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Automanage'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Automation'; RequiredVersion = '1.11.1'; }, 
               @{ModuleName = 'Az.Batch'; RequiredVersion = '3.7.0'; }, 
               @{ModuleName = 'Az.Billing'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Cdn'; RequiredVersion = '5.0.0'; }, 
               @{ModuleName = 'Az.CloudService'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.CognitiveServices'; RequiredVersion = '1.16.0'; }, 
               @{ModuleName = 'Az.Compute'; RequiredVersion = '10.2.0'; }, 
               @{ModuleName = 'Az.ConfidentialLedger'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.ConnectedMachine'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ContainerInstance'; RequiredVersion = '4.1.1'; }, 
               @{ModuleName = 'Az.ContainerRegistry'; RequiredVersion = '4.3.0'; }, 
               @{ModuleName = 'Az.CosmosDB'; RequiredVersion = '1.18.2'; }, 
               @{ModuleName = 'Az.DataBoxEdge'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.Databricks'; RequiredVersion = '1.10.0'; }, 
               @{ModuleName = 'Az.DataFactory'; RequiredVersion = '1.19.4'; }, 
               @{ModuleName = 'Az.DataLakeAnalytics'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.DataLakeStore'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.DataProtection'; RequiredVersion = '2.7.0'; }, 
               @{ModuleName = 'Az.DataShare'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.DesktopVirtualization'; RequiredVersion = '5.4.1'; }, 
               @{ModuleName = 'Az.DevCenter'; RequiredVersion = '2.0.2'; }, 
               @{ModuleName = 'Az.DevTestLabs'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Dns'; RequiredVersion = '1.3.1'; }, 
               @{ModuleName = 'Az.DnsResolver'; RequiredVersion = '1.1.1'; }, 
               @{ModuleName = 'Az.ElasticSan'; RequiredVersion = '1.4.1'; }, 
               @{ModuleName = 'Az.EventGrid'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.EventHub'; RequiredVersion = '5.4.0'; }, 
               @{ModuleName = 'Az.Fabric'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.FrontDoor'; RequiredVersion = '1.13.0'; }, 
               @{ModuleName = 'Az.Functions'; RequiredVersion = '4.2.1'; }, 
               @{ModuleName = 'Az.HDInsight'; RequiredVersion = '6.3.1'; }, 
               @{ModuleName = 'Az.HealthcareApis'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.HealthDataAIServices'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.IotHub'; RequiredVersion = '2.8.0'; }, 
               @{ModuleName = 'Az.KeyVault'; RequiredVersion = '6.3.1'; }, 
               @{ModuleName = 'Az.Kusto'; RequiredVersion = '2.4.0'; }, 
               @{ModuleName = 'Az.LambdaTest'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.LoadTesting'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.LogicApp'; RequiredVersion = '1.6.0'; }, 
               @{ModuleName = 'Az.MachineLearning'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.MachineLearningServices'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Maintenance'; RequiredVersion = '1.5.1'; }, 
               @{ModuleName = 'Az.ManagedServiceIdentity'; RequiredVersion = '2.0.0'; }, 
               @{ModuleName = 'Az.ManagedServices'; RequiredVersion = '3.1.2'; }, 
               @{ModuleName = 'Az.MarketplaceOrdering'; RequiredVersion = '2.2.0'; }, 
               @{ModuleName = 'Az.Migrate'; RequiredVersion = '2.9.0'; }, 
               @{ModuleName = 'Az.Monitor'; RequiredVersion = '6.0.3'; }, 
               @{ModuleName = 'Az.MySql'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.Network'; RequiredVersion = '7.19.0'; }, 
               @{ModuleName = 'Az.NetworkCloud'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.Nginx'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.NotificationHubs'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.OperationalInsights'; RequiredVersion = '3.3.0'; }, 
               @{ModuleName = 'Az.Oracle'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.PolicyInsights'; RequiredVersion = '1.7.1'; }, 
               @{ModuleName = 'Az.PostgreSql'; RequiredVersion = '1.4.0'; }, 
               @{ModuleName = 'Az.PowerBIEmbedded'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.PrivateDns'; RequiredVersion = '1.2.0'; }, 
               @{ModuleName = 'Az.RecoveryServices'; RequiredVersion = '7.8.0'; }, 
               @{ModuleName = 'Az.RedisCache'; RequiredVersion = '1.11.0'; }, 
               @{ModuleName = 'Az.RedisEnterpriseCache'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.Relay'; RequiredVersion = '2.1.2'; }, 
               @{ModuleName = 'Az.ResourceGraph'; RequiredVersion = '1.2.1'; }, 
               @{ModuleName = 'Az.ResourceMover'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Resources'; RequiredVersion = '8.1.0'; }, 
               @{ModuleName = 'Az.Security'; RequiredVersion = '1.8.0'; }, 
               @{ModuleName = 'Az.SecurityInsights'; RequiredVersion = '3.2.0'; }, 
               @{ModuleName = 'Az.ServiceBus'; RequiredVersion = '4.1.1'; }, 
               @{ModuleName = 'Az.ServiceFabric'; RequiredVersion = '3.6.0'; }, 
               @{ModuleName = 'Az.SignalR'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Sql'; RequiredVersion = '6.0.5'; }, 
               @{ModuleName = 'Az.SqlVirtualMachine'; RequiredVersion = '2.4.0'; }, 
               @{ModuleName = 'Az.StackHCI'; RequiredVersion = '2.6.1'; }, 
               @{ModuleName = 'Az.StackHCIVM'; RequiredVersion = '1.1.0'; }, 
               @{ModuleName = 'Az.Storage'; RequiredVersion = '9.1.0'; }, 
               @{ModuleName = 'Az.StorageAction'; RequiredVersion = '1.0.0'; }, 
               @{ModuleName = 'Az.StorageMover'; RequiredVersion = '1.5.0'; }, 
               @{ModuleName = 'Az.StorageSync'; RequiredVersion = '2.5.1'; }, 
               @{ModuleName = 'Az.StreamAnalytics'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Support'; RequiredVersion = '2.1.0'; }, 
               @{ModuleName = 'Az.Synapse'; RequiredVersion = '3.2.2'; }, 
               @{ModuleName = 'Az.TrafficManager'; RequiredVersion = '1.3.0'; }, 
               @{ModuleName = 'Az.Websites'; RequiredVersion = '3.4.1'; }, 
               @{ModuleName = 'Az.Workloads'; RequiredVersion = '1.0.0'; })

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ARM','ResourceManager','Linux','AzureAutomationNotSupported'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '14.3.0 - August 2025
Az.Accounts
* Fixed an issue where ''Clear-AzContext'' does not clear the token cache when broker is enabled.
* Added new parameter ''-ClaimsChallenge'' to ''Connect-AzAccount'' to support claims challenge authentication for MFA.
* Refined the error message when a cmdlet fails because of policy violations about Multi-Factor Authentication (MFA) to provide more actionable guidance.

Az.ArizeAI
* General availability for module Az.ArizeAI
* Upgraded the API version to 2024-10-01

Az.Compute
* Compute DiskRP related cmdlets will now use 2025-01-02 version of the DiskRP API.
* Upgraded SpotPlacementScore cmdlets to api version 2025-06-05

Az.CosmosDB
* Fixed issue where the restore command failed to detect the source account, even when it existed.

Az.DataLakeStore
* Added a new cmdlet GetAzureDataLakeStoreDeletedItemWithtoken to support pagination in  GetAzureDataLakeStoreDeletedItem

Az.DevCenter
* Added preannouncement breaking change messages.

Az.EventHub
* Added new cmdlets for Eventhubnetworksecurityperimeterconfiguration - ''Get-AzEventHubNetworkSecurityPerimeterConfigurationsForAssociation'', ''Get-AzEventHubNetworkSecurityPerimeterConfiguration''

Az.Fabric
* General availability for module Az.Fabric

Az.LambdaTest
* General availability for module Az.LambdaTest
* Upgraded the API version to 2024-02-01

Az.ManagedServices
* Update the outputs of breaking change announcements.

Az.Migrate
* Added ''-OsType'' as an optional parameter to command ''Set-AzMigrateLocalServerReplication'' to allow user-specified OS type.
* Fixed bugs in ''New-AzMigrateServerReplication'' caused by deprecation of ''Get-AzVmSize -location''
* Removed ''-TargetStoragePathId'' parameter from command ''New-AzMigrateLocalDiskMappingObject'' until the feature to associate each disk to their own storage container path is supported.
* Added ''-SourceApplianceName'' and ''-TargetApplianceName'' as required parameters to command ''New-AzMigrateLocalServerReplication'' to allow users to specify appliance pairs of their choosing.
* Enhanced resource validations in ''Initialize-AzMigrateLocalReplicationInfrastructure'' and ''New-AzMigrateLocalServerReplication''.

Az.Monitor
* Added breaking change announcement for below cmdlets from single object or fixed array to list.
  - ''Get-AzActivityLogAlert''
  - ''New-AzActivityLogAlert''
  - ''Update-AzActivityLogAlert''
  - ''New-AzActivityLogAlertAlertRuleAnyOfOrLeafConditionObject''
  - ''New-AzActivityLogAlertAlertRuleLeafConditionObject''
  - ''Get-AzAutoscalePredictiveMetric''
  - ''Get-AzAutoscaleSetting''
  - ''New-AzAutoscaleNotificationObject''
  - ''New-AzAutoscaleProfileObject''
  - ''New-AzAutoscaleScaleRuleMetricDimensionObject''
  - ''New-AzAutoscaleScaleRuleObject''
  - ''New-AzAutoscaleSetting''
  - ''Update-AzAutoscaleSetting''
  - ''Get-AzMonitorWorkspace''
  - ''New-AzMonitorWorkspace''
  - ''Update-AzMonitorWorkspace''
  - ''New-AzDiagnosticSetting''
  - ''New-AzSubscriptionDiagnosticSetting''
  - ''Get-AzDiagnosticSetting''
  - ''Get-AzDiagnosticSettingCategory''
  - ''Get-AzSubscriptionDiagnosticSetting''
  - ''Get-AzScheduledQueryRule''
  - ''New-AzScheduledQueryRule''
  - ''New-AzScheduledQueryRuleConditionObject''
  - ''New-AzScheduledQueryRuleDimensionObject''
  - ''Update-AzScheduledQueryRule''

Az.MySql
- Aligned with SimplySql, use a PSCredential object instead of UserName/Password parameters when calling Open-MySQLConnection
- Introduced a Timeout value when running Test-AzMySqlFlexibleServerConnect with long running query

Az.Network
* Returned appgw and agc in waf policy
* Updated cmdlet ''New-AzFirewallPolicyApplicationRule'' to use HTTPS as the default protocol when creating a new FQDN Tag application rule.
* Added ''EnableDnstapLogging'' parameter to ''New-AzFirewall''

Az.NetworkCloud
* Upgraded API version to 2025-02-01

Az.Nginx
* Added breaking change announcement for below cmdlets from fixed array to list.
  - ''Get-AzNginxConfiguration''
  - ''New-AzNginxConfiguration''
  - ''Get-AzNginxDeployment''
  - ''New-AzNginxDeployment''
  - ''Update-AzNginxDeployment''
  - ''Invoke-AzNginxAnalysisConfiguration''
  - ''New-AzNginxNetworkProfileObject''
* Added breaking change announcement for ''New-AzNginxDeployment'' and ''Update-AzNginxDeployment'' cmdlets.
    - Removed ''-IdentityType'' parameter to support new Managed Identity settings.
    - Removed ''-IdentityUserAssignedIdentity''.
* The parameters of the ''New-AzNginxDeployment'' and ''Update-AzNginxDeployment'' cmdlets will be changed by new Managed Identity settings.
    - Added ''-UserAssignedIdentity'' parameter. The type of ''UserAssignedIdentity'' is simplified to a list of strings that is used to specify the user''s assigned identity.
    - Added ''EnableSystemAssignedIdentity'' to enable/disable system-assigned identities.

Az.Oracle
* Upgraded to the stable version 2025-03-01

Az.PostgreSql
- Aligned with SimplySql, use a PSCredential object instead of UserName/Password parameters when calling Open-PostGreConnection
- Introduced a Timeout value when running Test-AzPostgreSqlFlexibleServerConnect with long running query

Az.RecoveryServices
* Added new optional parameter CVMOsDiskEncryptionSetId in Restore-AzRecoveryServicesBackupItem.

Az.Relay
* Update the outputs of breaking change announcements.

Az.Resources
* Added functionality for cmdlet ''GetAzureResourceGroup''[#27865]
* Added breaking change announcement for below cmdlets from array to list.
  - ''Get-AzRoleManagementPolicy''
  - ''Update-AzRoleManagementPolicy''
* Added support for exporting resource group templates as Bicep files
    - Added ''OutputFormat'' parameter to ''Export-AzResourceGroup'' cmdlet
    - Supported values: ''Json'' (default), ''Bicep''

Az.ServiceFabric
* Added parameter ''Location'' to allow users to specify a different node type location than the resource group location in cmdlet ''Add-AzServiceFabricNodeType''.
* Added parameter ''VmSize'' to allow for in-place sku swap for cmdlet ''Set-AzServiceFabricManagedNodeType''.
* Updated SFMC to latest api preview version ''2025-03-01-preview''

Az.Sql
* Updated ''DatabaseOperations'' Api to version ''2024-11-01-preview'' for .Net Sdk

Az.StackHCI
* Used fully qualified computer name and added warning for user to upgrade to solution.

Az.StorageSync
* Fixed security bug in token acquisition for MI server registration

Az.Synapse
* Fixed an error when remove artifact throw ''ArgumentNullException''
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoKgYJKoZIhvcNAQcCoIIoGzCCKBcCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCA92P2LoPwCsX1Q
# DKvG46uqeamzQbPL8s8eKf0gYcAud6CCDXYwggX0MIID3KADAgECAhMzAAAEhV6Z
# 7A5ZL83XAAAAAASFMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjUwNjE5MTgyMTM3WhcNMjYwNjE3MTgyMTM3WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDASkh1cpvuUqfbqxele7LCSHEamVNBfFE4uY1FkGsAdUF/vnjpE1dnAD9vMOqy
# 5ZO49ILhP4jiP/P2Pn9ao+5TDtKmcQ+pZdzbG7t43yRXJC3nXvTGQroodPi9USQi
# 9rI+0gwuXRKBII7L+k3kMkKLmFrsWUjzgXVCLYa6ZH7BCALAcJWZTwWPoiT4HpqQ
# hJcYLB7pfetAVCeBEVZD8itKQ6QA5/LQR+9X6dlSj4Vxta4JnpxvgSrkjXCz+tlJ
# 67ABZ551lw23RWU1uyfgCfEFhBfiyPR2WSjskPl9ap6qrf8fNQ1sGYun2p4JdXxe
# UAKf1hVa/3TQXjvPTiRXCnJPAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUuCZyGiCuLYE0aU7j5TFqY05kko0w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwNTM1OTAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBACjmqAp2Ci4sTHZci+qk
# tEAKsFk5HNVGKyWR2rFGXsd7cggZ04H5U4SV0fAL6fOE9dLvt4I7HBHLhpGdE5Uj
# Ly4NxLTG2bDAkeAVmxmd2uKWVGKym1aarDxXfv3GCN4mRX+Pn4c+py3S/6Kkt5eS
# DAIIsrzKw3Kh2SW1hCwXX/k1v4b+NH1Fjl+i/xPJspXCFuZB4aC5FLT5fgbRKqns
# WeAdn8DsrYQhT3QXLt6Nv3/dMzv7G/Cdpbdcoul8FYl+t3dmXM+SIClC3l2ae0wO
# lNrQ42yQEycuPU5OoqLT85jsZ7+4CaScfFINlO7l7Y7r/xauqHbSPQ1r3oIC+e71
# 5s2G3ClZa3y99aYx2lnXYe1srcrIx8NAXTViiypXVn9ZGmEkfNcfDiqGQwkml5z9
# nm3pWiBZ69adaBBbAFEjyJG4y0a76bel/4sDCVvaZzLM3TFbxVO9BQrjZRtbJZbk
# C3XArpLqZSfx53SuYdddxPX8pvcqFuEu8wcUeD05t9xNbJ4TtdAECJlEi0vvBxlm
# M5tzFXy2qZeqPMXHSQYqPgZ9jvScZ6NwznFD0+33kbzyhOSz/WuGbAu4cHZG8gKn
# lQVT4uA2Diex9DMs2WHiokNknYlLoUeWXW1QrJLpqO82TLyKTbBM/oZHAdIc0kzo
# STro9b3+vjn2809D0+SOOCVZMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGgowghoGAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAASFXpnsDlkvzdcAAAAABIUwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIFZzMfczAxNctXnOmp8YVwZ4
# q63jJPOPl/xJ4SDkbOOjMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAuoqlpTzZxopUpRjxmZTsc902Fa8Nj0w6uUuMCMCSHZ7rpe2tNQwSIJXt
# goWmPcd190LMnJ3FSXZiz6Ti5WbpoNmxWMkBYJVK2O+QVQ9ku97bXc9I1gijxGoa
# 42Nr5M5Oxmw58VJRfDupHmA1wb/VhsQ95Y3g8Z5Vp+j5qnaYmbUDWTKch16fL4bi
# kHJsX5Lq6lJdthTIWrJGyDUcsQgx5ohGM7EgO5fQBAfzbEBVMQ2QUHs/JW9o9BAw
# LdtLCvvIP0YHTDipt8TNOdj9jrbgBJ1FWlf4XFoB9ZfYCTW7P8j2Ew3oc7JI7VPP
# Y61eWnFh2JBccmpAiwr+2VhHwSjmOKGCF5QwgheQBgorBgEEAYI3AwMBMYIXgDCC
# F3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFSBgsq
# hkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCDGnIz0LIkh8+ofjKJPsks5DSUfyNmbDY5qYdPIGo1EZgIGaEtDfAOC
# GBMyMDI1MDczMDA0MTU0MC43NjhaMASAAgH0oIHRpIHOMIHLMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1l
# cmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046RjAwMi0w
# NUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wg
# ghHqMIIHIDCCBQigAwIBAgITMwAAAgU8dWyCRIfN/gABAAACBTANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yNTAxMzAxOTQy
# NDlaFw0yNjA0MjIxOTQyNDlaMIHLMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25z
# MScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046RjAwMi0wNUUwLUQ5NDcxJTAjBgNV
# BAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEB
# AQUAA4ICDwAwggIKAoICAQCSkvLfd7gF1r2wGdy85CFYXHUC8ywEyD4LRLv0WYEX
# eeZ0u5YuK7p2cXVzQmZPOHTN8TWqG2SPlUb+7PldzFDDAlR3vU8piOjmhu9rHW43
# M2dbor9jl9gluhzwUd2SciVGa7f9t67tM3KFKRSMXFtHKF3KwBB7aVo+b1qy5p9D
# Wlo2N5FGrBqHMEVlNyzreHYoDLL+m8fSsqMu/iYUqxzK5F4S7IY5NemAB8B+A3Qg
# wVIi64KJIfeKZUeiWKCTf4odUgP3AQilxh48P6z7AT4IA0dMEtKhYLFs4W/KNDMs
# Yr7KpQPKVCcC5E8uDHdKewubyzenkTxy4ff1N3g8yho5Pi9BfjR0VytrkmpDfep8
# JPwcb4BNOIXOo1pfdHZ8EvnR7JFZFQiqpMZFlO5CAuTYH8ujc5PUHlaMAJ8NEa9T
# FJTOSBrB7PRgeh/6NJ2xu9yxPh/kVN9BGss93MC6UjpoxeM4x70bwbwiK8SNHIO8
# D8cql7VSevUYbjN4NogFFwhBClhodE/zeGPq6y6ixD4z65IHY3zwFQbBVX/w+L/V
# HNn/BMGs2PGHnlRjO/Kk8NIpN4shkFQqA1fM08frrDSNEY9VKDtpsUpAF51Y1oQ6
# tJhWM1d3neCXh6b/6N+XeHORCwnY83K+pFMMhg8isXQb6KRl65kg8XYBd4JwkbKo
# VQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFHR6Wrs27b6+yJ3bEZ9o5NdL1bLwMB8G
# A1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCG
# Tmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUy
# MFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4w
# XAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2Vy
# dHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwG
# A1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQD
# AgeAMA0GCSqGSIb3DQEBCwUAA4ICAQAOuxk47b1i75V81Tx6xo10xNIr4zZxYVfk
# F5TFq2kndPHgzVyLnssw/HKkEZRCgZVpkKEJ6Y4jvG5tugMi+Wjt7hUMSipk+RpB
# 5gFQvh1xmAEL2flegzTWEsnj0wrESplI5Z3vgf2eGXAr/RcqGjSpouHbD2HY9Y3F
# 0Ol6FRDCV/HEGKRHzn2M5rQpFGSjacT4DkqVYmem/ArOfSvVojnKEIW914UxGtuh
# JSr9jOo5RqTX7GIqbtvN7zhWld+i3XxdhdNcflQz9YhoFqQexBenoIRgAPAtwH68
# xczr9LMC3l9ALEpnsvO0RiKPXF4l22/OfcFffaphnl/TDwkiJfxOyAMfUF3xI9+3
# izT1WX2CFs2RaOAq3dcohyJw+xRG0E8wkCHqkV57BbUBEzLX8L9lGJ1DoxYNpoDX
# 7iQzJ9Qdkypi5fv773E3Ch8A+toxeFp6FifQZyCc8IcIBlHyak6MbT6YTVQNgQ/h
# 8FF+S5OqP7CECFvIH2Kt2P0GlOu9C0BfashnTjodmtZFZsptUvirk/2HOLLjBiMj
# DwJsQAFAzJuz4ZtTyorrvER10Gl/mbmViHqhvNACfTzPiLfjDgyvp9s7/bHu/Cal
# KmeiJULGjh/lwAj5319pggsGJqbhJ4FbFc+oU5zffbm/rKjVZ8kxND3im10Qp41n
# 2t/qpyP6ETCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZI
# hvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAw
# DgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# MjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAy
# MDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoIC
# AQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25Phdg
# M/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPF
# dvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6
# GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBp
# Dco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50Zu
# yjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3E
# XzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0
# lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1q
# GFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ
# +QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PA
# PBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkw
# EgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxG
# NSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARV
# MFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWlj
# cm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAK
# BggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMC
# AYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvX
# zpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20v
# cGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYI
# KwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG
# 9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0x
# M7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmC
# VgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449
# xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wM
# nosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDS
# PeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2d
# Y3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxn
# GSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+Crvs
# QWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokL
# jzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL
# 6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNN
# MIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hp
# bmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jw
# b3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0aW9uczEn
# MCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkYwMDItMDVFMC1EOTQ3MSUwIwYDVQQD
# ExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQDV
# sH9p1tJn+krwCMvqOhVvXrbetKCBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7DO0TDAiGA8yMDI1MDcyOTIwNTc0
# OFoYDzIwMjUwNzMwMjA1NzQ4WjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDsM7RM
# AgEAMAcCAQACAgorMAcCAQACAhJLMAoCBQDsNQXMAgEAMDYGCisGAQQBhFkKBAIx
# KDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZI
# hvcNAQELBQADggEBAHNblnQ5adZMf66zkB25GIbOyiIj8lXsqYMzJz0GeatpAUSY
# bkc9HbWxpnpkeMc0Xq/nnpr9OzERlgqX9CaAboBsxGqvyHDnDluodbWgVgz0xqA8
# htp3jb+oGighYj/C78gDrEjFCzDqKSRSpBhoEMiCFmyY9SVYcbWf/soG2+CHxylW
# 7kNmKN9M6persl95f1OJH/sFWFQrfReD0h7acCw6zC+uqGK5r5KDYCMmoIiy3NLv
# bcvaxziWeWXIy0cea5E/y2lfWNqmfwg9RiPj7jydBKtoBcZirlXFMudlBup2F+lM
# t6qV+Nh3zrPXC3IUQfcXPm5peF3LYZ4WB7U9qI8xggQNMIIECQIBATCBkzB8MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNy
# b3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAgU8dWyCRIfN/gABAAACBTAN
# BglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMC8G
# CSqGSIb3DQEJBDEiBCBDqtySpMHNiiZnVfFgOjGrUVDiEh5Jm2CIejyS8jsp0DCB
# +gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIIANAz3ceY0umhdWLR2sJpq0OPqt
# JDTAYRmjHVkwEW9IMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAIFPHVsgkSHzf4AAQAAAgUwIgQgqYmfidUdgIbnQ69J12h6+1ps9lYa
# olzYltAtz/AdcQYwDQYJKoZIhvcNAQELBQAEggIAaFmekDTuLXTLwX2MIKbsd9hS
# k+QE5MOh+T9MjaK5gkI/1/hLKrIhucF/VQr9qK0joCRlcWxzIbQwzUBW7yoSGxjV
# wNw6S8GV/w5Qrg1vIrU63CtAd7WTCav0kYLZg7bcNUMb0EArdVUWhbZRxUJX2MKf
# 1BUQgelu1GuIrM4ZL8OcrLXdZBvkFkSv5OeOpM7s5bjkbqrMv6pZ3ogviG4QnxdM
# EWHnSmThbxCgmrWDhpGVk2QpPprsXn2Qnac/USiM4oOvgCek71KiCxzLggJEEKxB
# WfJqQnwddDid7ytVpDLYdhTS1XgvRM3PFQ9j5G6YkqHmDx0TDn5hk5qnMq2HNLH6
# yR+NSn+/oTXwi0bHpgswTNrDZ5tQZQOlxNUh2al4r+l7yTaia1BAxeA4mTscGfXL
# axNgrjTgL84wIZcKXybzPSohEI6UtqSvvaqDc917rkJ16bGdGNnJkvqmE/GLUp2G
# zq2FA+QNRZEJvmpcTvVOows6rVtbsXFQ3NaNp0G+796hsxqzfsv/xIbQTpiC8kiY
# M0XkSYegi/ycdFxXSB80rLu/XJhJAIvDiLd2G94EKX/lxJHdomoF2RLHYZHDDr3B
# D2o2M0gVuAulxOZaaOKmpTkEaW2GbNrCvZ/ho1Bd6UIBcV7UuOyTV1zlZ2YRgAIG
# x+h+QIh/ZyK3jdIUlj0=
# SIG # End signature block
