trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: node
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: 'default'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package -DskipTests=true'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(build.artifactstagingdirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'shopping-app'
        publishLocation: 'Container'
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonar-connection'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'shopping-app'
        cliProjectName: 'shopping-app'
        cliSources: '.'
        extraProperties: 'sonar.java.binaries=.'
    - task: SonarQubeAnalyze@5
      inputs:
        jdkversion: 'JAVA_HOME_11_X64'
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'shopping-app'
        scanPath: '.'
        format: 'HTML'
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-connection'
        repository: 'vaibhavkarade/shopping-app'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-connection'
        repository: 'vaibhavkarade/shopping-app'
        command: 'push'
        tags: 'latest'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker run -d --name shopping-app -p 8070:8070 vaibhavkarade/shopping-app:latest'

