#
# Module manifest for module 'Az.Network'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/30/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.Network.psm1'

# Version number of this module.
ModuleVersion = '7.19.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f554cfcd-9cbb-4021-b158-fe20f0497f82'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

For more information on Networking, please visit the following: https://learn.microsoft.com/azure/networking/networking-overview'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Microsoft.Azure.PowerShell.AutoMapper.dll', 
               'Microsoft.Azure.PowerShell.Network.Management.Sdk.dll', 
               'NetworkSecurityPerimeter.Autorest/bin/Az.NetworkSecurityPerimeter.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Network.generated.format.ps1xml', 
               'NetworkSecurityPerimeter.Autorest/Az.NetworkSecurityPerimeter.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('NetworkSecurityPerimeter.Autorest/Az.NetworkSecurityPerimeter.psm1')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Get-AzNetworkSecurityPerimeter', 
               'Get-AzNetworkSecurityPerimeterAccessRule', 
               'Get-AzNetworkSecurityPerimeterAssociableResourceType', 
               'Get-AzNetworkSecurityPerimeterAssociation', 
               'Get-AzNetworkSecurityPerimeterLink', 
               'Get-AzNetworkSecurityPerimeterLinkReference', 
               'Get-AzNetworkSecurityPerimeterLoggingConfiguration', 
               'Get-AzNetworkSecurityPerimeterProfile', 
               'New-AzNetworkSecurityPerimeter', 
               'New-AzNetworkSecurityPerimeterAccessRule', 
               'New-AzNetworkSecurityPerimeterAssociation', 
               'New-AzNetworkSecurityPerimeterLink', 
               'New-AzNetworkSecurityPerimeterLoggingConfiguration', 
               'New-AzNetworkSecurityPerimeterProfile', 
               'Remove-AzNetworkSecurityPerimeter', 
               'Remove-AzNetworkSecurityPerimeterAccessRule', 
               'Remove-AzNetworkSecurityPerimeterAssociation', 
               'Remove-AzNetworkSecurityPerimeterLink', 
               'Remove-AzNetworkSecurityPerimeterLinkReference', 
               'Remove-AzNetworkSecurityPerimeterLoggingConfiguration', 
               'Remove-AzNetworkSecurityPerimeterProfile', 
               'Update-AzNetworkSecurityPerimeter', 
               'Update-AzNetworkSecurityPerimeterAccessRule', 
               'Update-AzNetworkSecurityPerimeterAssociation', 
               'Update-AzNetworkSecurityPerimeterLink', 
               'Update-AzNetworkSecurityPerimeterLoggingConfiguration'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-AzApplicationGatewayAuthenticationCertificate', 
               'Add-AzApplicationGatewayBackendAddressPool', 
               'Add-AzApplicationGatewayBackendHttpSetting', 
               'Add-AzApplicationGatewayBackendSetting', 
               'Add-AzApplicationGatewayCustomError', 
               'Add-AzApplicationGatewayFrontendIPConfig', 
               'Add-AzApplicationGatewayFrontendPort', 
               'Add-AzApplicationGatewayHttpListener', 
               'Add-AzApplicationGatewayHttpListenerCustomError', 
               'Add-AzApplicationGatewayIPConfiguration', 
               'Add-AzApplicationGatewayListener', 
               'Add-AzApplicationGatewayPrivateLinkConfiguration', 
               'Add-AzApplicationGatewayProbeConfig', 
               'Add-AzApplicationGatewayRedirectConfiguration', 
               'Add-AzApplicationGatewayRequestRoutingRule', 
               'Add-AzApplicationGatewayRewriteRuleSet', 
               'Add-AzApplicationGatewayRoutingRule', 
               'Add-AzApplicationGatewaySslCertificate', 
               'Add-AzApplicationGatewaySslProfile', 
               'Add-AzApplicationGatewayTrustedClientCertificate', 
               'Add-AzApplicationGatewayTrustedRootCertificate', 
               'Add-AzApplicationGatewayUrlPathMapConfig', 'Add-AzDelegation', 
               'Add-AzExpressRouteCircuitAuthorization', 
               'Add-AzExpressRouteCircuitConnectionConfig', 
               'Add-AzExpressRouteCircuitMicrosoftPeeringPrefixConfig', 
               'Add-AzExpressRouteCircuitPeeringConfig', 
               'Add-AzExpressRouteCrossConnectionPeering', 
               'Add-AzExpressRoutePortAuthorization', 
               'Add-AzLoadBalancerBackendAddressPoolConfig', 
               'Add-AzLoadBalancerFrontendIpConfig', 
               'Add-AzLoadBalancerInboundNatPoolConfig', 
               'Add-AzLoadBalancerInboundNatRuleConfig', 
               'Add-AzLoadBalancerOutboundRuleConfig', 
               'Add-AzLoadBalancerProbeConfig', 'Add-AzLoadBalancerRuleConfig', 
               'Add-AzNetworkInterfaceIpConfig', 'Add-AzNetworkInterfaceTapConfig', 
               'Add-AzNetworkSecurityRuleConfig', 'Add-AzRouteConfig', 
               'Add-AzRouteFilterRuleConfig', 'Add-AzRouteServerPeer', 
               'Add-AzRoutingPolicy', 'Add-AzServiceEndpointPolicyDefinition', 
               'Add-AzVirtualHubRoute', 'Add-AzVirtualHubRouteTable', 
               'Add-AzVirtualNetworkGatewayIpConfig', 
               'Add-AzVirtualNetworkPeering', 'Add-AzVirtualNetworkSubnetConfig', 
               'Add-AzVirtualRouterPeer', 'Add-AzVpnClientRevokedCertificate', 
               'Add-AzVpnClientRootCertificate', 
               'Approve-AzPrivateEndpointConnection', 
               'Convert-AzNetworkWatcherClassicConnectionMonitor', 
               'Deny-AzPrivateEndpointConnection', 'Deploy-AzFirewallPolicy', 
               'Deploy-AzNetworkManagerCommit', 
               'Disconnect-AzP2SVpnGatewayVpnConnection', 
               'Disconnect-AzVirtualNetworkGatewayVpnConnection', 
               'Get-AzApplicationGateway', 
               'Get-AzApplicationGatewayAuthenticationCertificate', 
               'Get-AzApplicationGatewayAutoscaleConfiguration', 
               'Get-AzApplicationGatewayAvailableServerVariableAndHeader', 
               'Get-AzApplicationGatewayAvailableSslOption', 
               'Get-AzApplicationGatewayAvailableWafRuleSet', 
               'Get-AzApplicationGatewayBackendAddressPool', 
               'Get-AzApplicationGatewayBackendHealth', 
               'Get-AzApplicationGatewayBackendHttpSetting', 
               'Get-AzApplicationGatewayBackendSetting', 
               'Get-AzApplicationGatewayClientAuthConfiguration', 
               'Get-AzApplicationGatewayConnectionDraining', 
               'Get-AzApplicationGatewayCustomError', 
               'Get-AzApplicationGatewayFirewallPolicy', 
               'Get-AzApplicationGatewayFrontendIPConfig', 
               'Get-AzApplicationGatewayFrontendPort', 
               'Get-AzApplicationGatewayHttpListener', 
               'Get-AzApplicationGatewayHttpListenerCustomError', 
               'Get-AzApplicationGatewayIdentity', 
               'Get-AzApplicationGatewayIPConfiguration', 
               'Get-AzApplicationGatewayListener', 
               'Get-AzApplicationGatewayPrivateLinkConfiguration', 
               'Get-AzApplicationGatewayProbeConfig', 
               'Get-AzApplicationGatewayRedirectConfiguration', 
               'Get-AzApplicationGatewayRequestRoutingRule', 
               'Get-AzApplicationGatewayRewriteRuleSet', 
               'Get-AzApplicationGatewayRoutingRule', 
               'Get-AzApplicationGatewaySku', 
               'Get-AzApplicationGatewaySslCertificate', 
               'Get-AzApplicationGatewaySslPolicy', 
               'Get-AzApplicationGatewaySslPredefinedPolicy', 
               'Get-AzApplicationGatewaySslProfile', 
               'Get-AzApplicationGatewaySslProfilePolicy', 
               'Get-AzApplicationGatewayTrustedClientCertificate', 
               'Get-AzApplicationGatewayTrustedRootCertificate', 
               'Get-AzApplicationGatewayUrlPathMapConfig', 
               'Get-AzApplicationGatewayWafDynamicManifest', 
               'Get-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'Get-AzApplicationSecurityGroup', 
               'Get-AzAutoApprovedPrivateLinkService', 
               'Get-AzAvailablePrivateEndpointType', 'Get-AzAvailableServiceAlias', 
               'Get-AzAvailableServiceDelegation', 'Get-AzBastion', 
               'Get-AzBastionShareableLink', 'Get-AzBgpServiceCommunity', 
               'Get-AzCustomIpPrefix', 'Get-AzDdosProtectionPlan', 
               'Get-AzDelegation', 'Get-AzEffectiveNetworkSecurityGroup', 
               'Get-AzEffectiveRouteTable', 'Get-AzExpressRouteCircuit', 
               'Get-AzExpressRouteCircuitARPTable', 
               'Get-AzExpressRouteCircuitAuthorization', 
               'Get-AzExpressRouteCircuitConnectionConfig', 
               'Get-AzExpressRouteCircuitMicrosoftPeeringPrefixConfig', 
               'Get-AzExpressRouteCircuitPeeringConfig', 
               'Get-AzExpressRouteCircuitRouteTable', 
               'Get-AzExpressRouteCircuitRouteTableSummary', 
               'Get-AzExpressRouteCircuitStat', 'Get-AzExpressRouteConnection', 
               'Get-AzExpressRouteCrossConnection', 
               'Get-AzExpressRouteCrossConnectionArpTable', 
               'Get-AzExpressRouteCrossConnectionPeering', 
               'Get-AzExpressRouteCrossConnectionRouteTable', 
               'Get-AzExpressRouteCrossConnectionRouteTableSummary', 
               'Get-AzExpressRouteGateway', 'Get-AzExpressRoutePort', 
               'Get-AzExpressRoutePortAuthorization', 
               'Get-AzExpressRoutePortIdentity', 
               'Get-AzExpressRoutePortLinkConfig', 
               'Get-AzExpressRoutePortsLocation', 
               'Get-AzExpressRouteServiceProvider', 'Get-AzFirewall', 
               'Get-AzFirewallFqdnTag', 'Get-AzFirewallLearnedIpPrefix', 
               'Get-AzFirewallPolicy', 'Get-AzFirewallPolicyDraft', 
               'Get-AzFirewallPolicyRuleCollectionGroup', 
               'Get-AzFirewallPolicyRuleCollectionGroupDraft', 
               'Get-AzIpAllocation', 'Get-AzIpGroup', 'Get-AzLoadBalancer', 
               'Get-AzLoadBalancerBackendAddressInboundNatRulePortMapping', 
               'Get-AzLoadBalancerBackendAddressPool', 
               'Get-AzLoadBalancerBackendAddressPoolConfig', 
               'Get-AzLoadBalancerFrontendIpConfig', 
               'Get-AzLoadBalancerInboundNatPoolConfig', 
               'Get-AzLoadBalancerInboundNatRuleConfig', 
               'Get-AzLoadBalancerOutboundRuleConfig', 
               'Get-AzLoadBalancerProbeConfig', 'Get-AzLoadBalancerRuleConfig', 
               'Get-AzLoadBalancerRuleHealth', 'Get-AzLocalNetworkGateway', 
               'Get-AzNatGateway', 'Get-AzNetworkInterface', 
               'Get-AzNetworkInterfaceIpConfig', 'Get-AzNetworkInterfaceTapConfig', 
               'Get-AzNetworkManager', 
               'Get-AzNetworkManagerActiveConnectivityConfiguration', 
               'Get-AzNetworkManagerActiveSecurityAdminRule', 
               'Get-AzNetworkManagerAssociatedResourcesList', 
               'Get-AzNetworkManagerConnectivityConfiguration', 
               'Get-AzNetworkManagerDeploymentStatus', 
               'Get-AzNetworkManagerEffectiveConnectivityConfiguration', 
               'Get-AzNetworkManagerEffectiveSecurityAdminRule', 
               'Get-AzNetworkManagerGroup', 'Get-AzNetworkManagerIpamPool', 
               'Get-AzNetworkManagerIpamPoolStaticCidr', 
               'Get-AzNetworkManagerIpamPoolUsage', 
               'Get-AzNetworkManagerManagementGroupConnection', 
               'Get-AzNetworkManagerRoutingConfiguration', 
               'Get-AzNetworkManagerRoutingRule', 
               'Get-AzNetworkManagerRoutingRuleCollection', 
               'Get-AzNetworkManagerScopeConnection', 
               'Get-AzNetworkManagerSecurityAdminConfiguration', 
               'Get-AzNetworkManagerSecurityAdminRule', 
               'Get-AzNetworkManagerSecurityAdminRuleCollection', 
               'Get-AzNetworkManagerSecurityUserConfiguration', 
               'Get-AzNetworkManagerSecurityUserRule', 
               'Get-AzNetworkManagerSecurityUserRuleCollection', 
               'Get-AzNetworkManagerStaticMember', 
               'Get-AzNetworkManagerSubscriptionConnection', 
               'Get-AzNetworkManagerVerifierWorkspace', 
               'Get-AzNetworkManagerVerifierWorkspaceReachabilityAnalysisIntent', 
               'Get-AzNetworkManagerVerifierWorkspaceReachabilityAnalysisRun', 
               'Get-AzNetworkProfile', 'Get-AzNetworkSecurityGroup', 
               'Get-AzNetworkSecurityRuleConfig', 'Get-AzNetworkServiceTag', 
               'Get-AzNetworkUsage', 'Get-AzNetworkVirtualAppliance', 
               'Get-AzNetworkVirtualApplianceBootDiagnostics', 
               'Get-AzNetworkVirtualApplianceConnection', 
               'Get-AzNetworkVirtualApplianceSku', 'Get-AzNetworkWatcher', 
               'Get-AzNetworkWatcherConnectionMonitor', 
               'Get-AzNetworkWatcherFlowLog', 'Get-AzNetworkWatcherFlowLogStatus', 
               'Get-AzNetworkWatcherNextHop', 'Get-AzNetworkWatcherPacketCapture', 
               'Get-AzNetworkWatcherReachabilityProvidersList', 
               'Get-AzNetworkWatcherReachabilityReport', 
               'Get-AzNetworkWatcherSecurityGroupView', 
               'Get-AzNetworkWatcherTopology', 
               'Get-AzNetworkWatcherTroubleshootingResult', 'Get-AzP2sVpnGateway', 
               'Get-AzP2sVpnGatewayConnectionHealth', 
               'Get-AzP2sVpnGatewayDetailedConnectionHealth', 
               'Get-AzP2sVpnGatewayVpnProfile', 'Get-AzPrivateDnsZoneGroup', 
               'Get-AzPrivateEndpoint', 'Get-AzPrivateEndpointConnection', 
               'Get-AzPrivateLinkResource', 'Get-AzPrivateLinkService', 
               'Get-AzPublicIpAddress', 'Get-AzPublicIpPrefix', 'Get-AzRouteConfig', 
               'Get-AzRouteFilter', 'Get-AzRouteFilterRuleConfig', 'Get-AzRouteMap', 
               'Get-AzRouteServer', 'Get-AzRouteServerPeer', 
               'Get-AzRouteServerPeerAdvertisedRoute', 
               'Get-AzRouteServerPeerLearnedRoute', 'Get-AzRouteTable', 
               'Get-AzRoutingIntent', 'Get-AzRoutingPolicy', 
               'Get-AzSecurityPartnerProvider', 'Get-AzServiceEndpointPolicy', 
               'Get-AzServiceEndpointPolicyDefinition', 'Get-AzVHubEffectiveRoute', 
               'Get-AzVHubInboundRoute', 'Get-AzVHubOutboundRoute', 
               'Get-AzVHubRouteTable', 'Get-AzVirtualApplianceSite', 
               'Get-AzVirtualHub', 'Get-AzVirtualHubBgpConnection', 
               'Get-AzVirtualHubRouteTable', 'Get-AzVirtualHubVnetConnection', 
               'Get-AzVirtualNetwork', 
               'Get-AzVirtualNetworkAvailableEndpointService', 
               'Get-AzVirtualNetworkGateway', 
               'Get-AzVirtualNetworkGatewayAdvertisedRoute', 
               'Get-AzVirtualNetworkGatewayBGPPeerStatus', 
               'Get-AzVirtualNetworkGatewayConnection', 
               'Get-AzVirtualNetworkGatewayConnectionIkeSa', 
               'Get-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Get-AzVirtualNetworkGatewayConnectionVpnDeviceConfigScript', 
               'Get-AzVirtualNetworkGatewayLearnedRoute', 
               'Get-AzVirtualNetworkGatewayNatRule', 
               'Get-AzVirtualNetworkGatewaySupportedVpnDevice', 
               'Get-AzVirtualNetworkGatewayVpnClientConnectionHealth', 
               'Get-AzVirtualNetworkPeering', 'Get-AzVirtualNetworkSubnetConfig', 
               'Get-AzVirtualNetworkTap', 'Get-AzVirtualNetworkUsageList', 
               'Get-AzVirtualRouter', 'Get-AzVirtualRouterPeer', 
               'Get-AzVirtualRouterPeerAdvertisedRoute', 
               'Get-AzVirtualRouterPeerLearnedRoute', 'Get-AzVirtualWan', 
               'Get-AzVirtualWanVpnConfiguration', 
               'Get-AzVirtualWanVpnServerConfiguration', 
               'Get-AzVirtualWanVpnServerConfigurationVpnProfile', 
               'Get-AzVpnClientConfiguration', 'Get-AzVpnClientIpsecParameter', 
               'Get-AzVpnClientPackage', 'Get-AzVpnClientRevokedCertificate', 
               'Get-AzVpnClientRootCertificate', 'Get-AzVpnConnection', 
               'Get-AzVpnGateway', 'Get-AzVpnGatewayNatRule', 
               'Get-AzVpnServerConfiguration', 
               'Get-AzVpnServerConfigurationPolicyGroup', 'Get-AzVpnSite', 
               'Get-AzVpnSiteLinkConnectionIkeSa', 
               'Invoke-AzFirewallPacketCapture', 
               'Invoke-AzNetworkWatcherNetworkConfigurationDiagnostic', 
               'Invoke-AzVirtualNetworkGatewayAbortMigration', 
               'Invoke-AzVirtualNetworkGatewayCommitMigration', 
               'Invoke-AzVirtualNetworkGatewayExecuteMigration', 
               'Invoke-AzVirtualNetworkGatewayPrepareMigration', 
               'Move-AzExpressRouteCircuit', 'New-AzApplicationGateway', 
               'New-AzApplicationGatewayAuthenticationCertificate', 
               'New-AzApplicationGatewayAutoscaleConfiguration', 
               'New-AzApplicationGatewayBackendAddressPool', 
               'New-AzApplicationGatewayBackendHttpSetting', 
               'New-AzApplicationGatewayBackendSetting', 
               'New-AzApplicationGatewayClientAuthConfiguration', 
               'New-AzApplicationGatewayConnectionDraining', 
               'New-AzApplicationGatewayCustomError', 
               'New-AzApplicationGatewayFirewallCondition', 
               'New-AzApplicationGatewayFirewallCustomRule', 
               'New-AzApplicationGatewayFirewallCustomRuleGroupByUserSession', 
               'New-AzApplicationGatewayFirewallCustomRuleGroupByVariable', 
               'New-AzApplicationGatewayFirewallDisabledRuleGroupConfig', 
               'New-AzApplicationGatewayFirewallExclusionConfig', 
               'New-AzApplicationGatewayFirewallMatchVariable', 
               'New-AzApplicationGatewayFirewallPolicyException', 
               'New-AzApplicationGatewayFirewallPolicy', 
               'New-AzApplicationGatewayFirewallPolicyExclusion', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRule', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleGroup', 
               'New-AzApplicationGatewayFirewallPolicyExclusionManagedRuleSet', 
               'New-AzApplicationGatewayFirewallPolicyLogScrubbingConfiguration', 
               'New-AzApplicationGatewayFirewallPolicyLogScrubbingRule', 
               'New-AzApplicationGatewayFirewallPolicyManagedRule', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleGroupOverride', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleOverride', 
               'New-AzApplicationGatewayFirewallPolicyManagedRuleSet', 
               'New-AzApplicationGatewayFirewallPolicySetting', 
               'New-AzApplicationGatewayFrontendIPConfig', 
               'New-AzApplicationGatewayFrontendPort', 
               'New-AzApplicationGatewayHeaderValueMatcher', 
               'New-AzApplicationGatewayHttpListener', 
               'New-AzApplicationGatewayIdentity', 
               'New-AzApplicationGatewayIPConfiguration', 
               'New-AzApplicationGatewayListener', 
               'New-AzApplicationGatewayPathRuleConfig', 
               'New-AzApplicationGatewayPrivateLinkConfiguration', 
               'New-AzApplicationGatewayPrivateLinkIpConfiguration', 
               'New-AzApplicationGatewayProbeConfig', 
               'New-AzApplicationGatewayProbeHealthResponseMatch', 
               'New-AzApplicationGatewayRedirectConfiguration', 
               'New-AzApplicationGatewayRequestRoutingRule', 
               'New-AzApplicationGatewayRewriteRule', 
               'New-AzApplicationGatewayRewriteRuleActionSet', 
               'New-AzApplicationGatewayRewriteRuleCondition', 
               'New-AzApplicationGatewayRewriteRuleHeaderConfiguration', 
               'New-AzApplicationGatewayRewriteRuleSet', 
               'New-AzApplicationGatewayRewriteRuleUrlConfiguration', 
               'New-AzApplicationGatewayRoutingRule', 
               'New-AzApplicationGatewaySku', 
               'New-AzApplicationGatewaySslCertificate', 
               'New-AzApplicationGatewaySslPolicy', 
               'New-AzApplicationGatewaySslProfile', 
               'New-AzApplicationGatewayTrustedClientCertificate', 
               'New-AzApplicationGatewayTrustedRootCertificate', 
               'New-AzApplicationGatewayUrlPathMapConfig', 
               'New-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'New-AzApplicationSecurityGroup', 'New-AzBastion', 
               'New-AzBastionShareableLink', 'New-AzContainerNicConfig', 
               'New-AzContainerNicConfigIpConfig', 'New-AzCustomIpPrefix', 
               'New-AzDdosProtectionPlan', 'New-AzDelegation', 
               'New-AzExpressRouteCircuit', 
               'New-AzExpressRouteCircuitAuthorization', 
               'New-AzExpressRouteCircuitPeeringConfig', 
               'New-AzExpressRouteConnection', 'New-AzExpressRouteGateway', 
               'New-AzExpressRoutePort', 'New-AzExpressRoutePortIdentity', 
               'New-AzExpressRoutePortLOA', 'New-AzFirewall', 
               'New-AzFirewallApplicationRule', 
               'New-AzFirewallApplicationRuleCollection', 
               'New-AzFirewallHubIpAddress', 'New-AzFirewallHubPublicIpAddress', 
               'New-AzFirewallNatRule', 'New-AzFirewallNatRuleCollection', 
               'New-AzFirewallNetworkRule', 'New-AzFirewallNetworkRuleCollection', 
               'New-AzFirewallPacketCaptureParameter', 
               'New-AzFirewallPacketCaptureRule', 'New-AzFirewallPolicy', 
               'New-AzFirewallPolicyApplicationRule', 
               'New-AzFirewallPolicyApplicationRuleCustomHttpHeader', 
               'New-AzFirewallPolicyDnsSetting', 'New-AzFirewallPolicyDraft', 
               'New-AzFirewallPolicyExplicitProxy', 
               'New-AzFirewallPolicyFilterRuleCollection', 
               'New-AzFirewallPolicyIntrusionDetection', 
               'New-AzFirewallPolicyIntrusionDetectionBypassTraffic', 
               'New-AzFirewallPolicyIntrusionDetectionSignatureOverride', 
               'New-AzFirewallPolicyNatRule', 
               'New-AzFirewallPolicyNatRuleCollection', 
               'New-AzFirewallPolicyNetworkRule', 
               'New-AzFirewallPolicyRuleCollectionGroup', 
               'New-AzFirewallPolicyRuleCollectionGroupDraft', 
               'New-AzFirewallPolicySnat', 'New-AzFirewallPolicySqlSetting', 
               'New-AzFirewallPolicyThreatIntelWhitelist', 
               'New-AzFirewallPublicIpAddress', 
               'New-AzFirewallThreatIntelWhitelist', 
               'New-AzGatewayCustomBgpIpConfigurationObject', 'New-AzIpAllocation', 
               'New-AzIpConfigurationBgpPeeringAddressObject', 'New-AzIpGroup', 
               'New-AzIpsecPolicy', 'New-AzIpsecTrafficSelectorPolicy', 
               'New-AzLoadBalancer', 'New-AzLoadBalancerBackendAddressConfig', 
               'New-AzLoadBalancerBackendAddressPool', 
               'New-AzLoadBalancerBackendAddressPoolConfig', 
               'New-AzLoadBalancerBackendAddressPoolTunnelInterfaceConfig', 
               'New-AzLoadBalancerFrontendIpConfig', 
               'New-AzLoadBalancerInboundNatPoolConfig', 
               'New-AzLoadBalancerInboundNatRuleConfig', 
               'New-AzLoadBalancerOutboundRuleConfig', 
               'New-AzLoadBalancerProbeConfig', 'New-AzLoadBalancerRuleConfig', 
               'New-AzLocalNetworkGateway', 'New-AzNatGateway', 
               'New-AzNetworkInterface', 'New-AzNetworkInterfaceIpConfig', 
               'New-AzNetworkManager', 'New-AzNetworkManagerAddressPrefixItem', 
               'New-AzNetworkManagerConnectivityConfiguration', 
               'New-AzNetworkManagerConnectivityGroupItem', 
               'New-AzNetworkManagerGroup', 'New-AzNetworkManagerHub', 
               'New-AzNetworkManagerIpamPool', 
               'New-AzNetworkManagerIpamPoolStaticCidr', 
               'New-AzNetworkManagerIPTraffic', 
               'New-AzNetworkManagerManagementGroupConnection', 
               'New-AzNetworkManagerRoutingConfiguration', 
               'New-AzNetworkManagerRoutingGroupItem', 
               'New-AzNetworkManagerRoutingRule', 
               'New-AzNetworkManagerRoutingRuleCollection', 
               'New-AzNetworkManagerRoutingRuleDestination', 
               'New-AzNetworkManagerRoutingRuleNextHop', 
               'New-AzNetworkManagerScope', 'New-AzNetworkManagerScopeConnection', 
               'New-AzNetworkManagerSecurityAdminConfiguration', 
               'New-AzNetworkManagerSecurityAdminRule', 
               'New-AzNetworkManagerSecurityAdminRuleCollection', 
               'New-AzNetworkManagerSecurityGroupItem', 
               'New-AzNetworkManagerSecurityUserConfiguration', 
               'New-AzNetworkManagerSecurityUserGroupItem', 
               'New-AzNetworkManagerSecurityUserRule', 
               'New-AzNetworkManagerSecurityUserRuleCollection', 
               'New-AzNetworkManagerStaticMember', 
               'New-AzNetworkManagerSubscriptionConnection', 
               'New-AzNetworkManagerVerifierWorkspace', 
               'New-AzNetworkManagerVerifierWorkspaceReachabilityAnalysisIntent', 
               'New-AzNetworkManagerVerifierWorkspaceReachabilityAnalysisRun', 
               'New-AzNetworkProfile', 'New-AzNetworkSecurityGroup', 
               'New-AzNetworkSecurityRuleConfig', 'New-AzNetworkVirtualAppliance', 
               'New-AzNetworkWatcher', 'New-AzNetworkWatcherConnectionMonitor', 
               'New-AzNetworkWatcherConnectionMonitorEndpointObject', 
               'New-AzNetworkWatcherConnectionMonitorEndpointScopeItemObject', 
               'New-AzNetworkWatcherConnectionMonitorObject', 
               'New-AzNetworkWatcherConnectionMonitorOutputObject', 
               'New-AzNetworkWatcherConnectionMonitorProtocolConfigurationObject', 
               'New-AzNetworkWatcherConnectionMonitorTestConfigurationObject', 
               'New-AzNetworkWatcherConnectionMonitorTestGroupObject', 
               'New-AzNetworkWatcherFlowLog', 
               'New-AzNetworkWatcherNetworkConfigurationDiagnosticProfile', 
               'New-AzNetworkWatcherPacketCapture', 
               'New-AzNetworkWatcherPacketCaptureV2', 
               'New-AzNetworkWatcherProtocolConfiguration', 
               'New-AzO365PolicyProperty', 'New-AzOffice365PolicyProperty', 
               'New-AzP2sVpnGateway', 'New-AzPacketCaptureFilterConfig', 
               'New-AzPacketCaptureSettingsConfig', 
               'New-AzPacketCaptureScopeConfig', 'New-AzPrivateDnsZoneConfig', 
               'New-AzPrivateDnsZoneGroup', 'New-AzPrivateEndpoint', 
               'New-AzPrivateEndpointIpConfiguration', 'New-AzPrivateLinkService', 
               'New-AzPrivateLinkServiceConnection', 
               'New-AzPrivateLinkServiceIpConfig', 'New-AzPublicIpAddress', 
               'New-AzPublicIpPrefix', 'New-AzPublicIpTag', 'New-AzRadiusServer', 
               'New-AzRouteConfig', 'New-AzRouteFilter', 
               'New-AzRouteFilterRuleConfig', 'New-AzRouteMap', 'New-AzRouteMapRule', 
               'New-AzRouteMapRuleAction', 'New-AzRouteMapRuleActionParameter', 
               'New-AzRouteMapRuleCriterion', 'New-AzRouteServer', 
               'New-AzRouteTable', 'New-AzRoutingConfiguration', 
               'New-AzRoutingIntent', 'New-AzRoutingPolicy', 
               'New-AzSaaSNetworkVirtualAppliance', 
               'New-AzSecurityPartnerProvider', 'New-AzServiceEndpointPolicy', 
               'New-AzServiceEndpointPolicyDefinition', 'New-AzStaticRoute', 
               'New-AzVHubRoute', 'New-AzVHubRouteTable', 
               'New-AzVirtualApplianceAdditionalNicProperty', 
               'New-AzVirtualApplianceInboundSecurityRulesProperty', 
               'New-AzVirtualApplianceInternetIngressIpsProperty', 
               'New-AzVirtualApplianceIpConfiguration', 
               'New-AzVirtualApplianceNetworkInterfaceConfiguration', 
               'New-AzVirtualApplianceNetworkProfile', 
               'New-AzVirtualApplianceSite', 'New-AzVirtualApplianceSkuProperty', 
               'New-AzVirtualHub', 'New-AzVirtualHubBgpConnection', 
               'New-AzVirtualHubRoute', 'New-AzVirtualHubRouteTable', 
               'New-AzVirtualHubVnetConnection', 'New-AzVirtualNetwork', 
               'New-AzVirtualNetworkGateway', 
               'New-AzVirtualNetworkGatewayConnection', 
               'New-AzVirtualNetworkGatewayIpConfig', 
               'New-AzVirtualNetworkGatewayMigrationParameter', 
               'New-AzVirtualNetworkGatewayNatRule', 
               'New-AzVirtualNetworkGatewayPolicyGroup', 
               'New-AzVirtualNetworkGatewayPolicyGroupMember', 
               'New-AzVirtualNetworkSubnetConfig', 'New-AzVirtualNetworkTap', 
               'New-AzVirtualRouter', 'New-AzVirtualRouterAutoScaleConfiguration', 
               'New-AzVirtualWan', 'New-AzVpnClientConfiguration', 
               'New-AzVpnClientConnectionConfiguration', 
               'New-AzVpnClientIpsecParameter', 'New-AzVpnClientIpsecPolicy', 
               'New-AzVpnClientRevokedCertificate', 
               'New-AzVpnClientRootCertificate', 'New-AzVpnConnection', 
               'New-AzVpnGateway', 'New-AzVpnGatewayNatRule', 
               'New-AzVpnServerConfiguration', 
               'New-AzVpnServerConfigurationPolicyGroup', 'New-AzVpnSite', 
               'New-AzVpnSiteLink', 'New-AzVpnSiteLinkConnection', 
               'Remove-AzApplicationGateway', 
               'Remove-AzApplicationGatewayAuthenticationCertificate', 
               'Remove-AzApplicationGatewayAutoscaleConfiguration', 
               'Remove-AzApplicationGatewayBackendAddressPool', 
               'Remove-AzApplicationGatewayBackendHttpSetting', 
               'Remove-AzApplicationGatewayBackendSetting', 
               'Remove-AzApplicationGatewayClientAuthConfiguration', 
               'Remove-AzApplicationGatewayConnectionDraining', 
               'Remove-AzApplicationGatewayCustomError', 
               'Remove-AzApplicationGatewayFirewallCustomRule', 
               'Remove-AzApplicationGatewayFirewallPolicy', 
               'Remove-AzApplicationGatewayFrontendIPConfig', 
               'Remove-AzApplicationGatewayFrontendPort', 
               'Remove-AzApplicationGatewayHttpListener', 
               'Remove-AzApplicationGatewayHttpListenerCustomError', 
               'Remove-AzApplicationGatewayIdentity', 
               'Remove-AzApplicationGatewayIPConfiguration', 
               'Remove-AzApplicationGatewayListener', 
               'Remove-AzApplicationGatewayPrivateLinkConfiguration', 
               'Remove-AzApplicationGatewayProbeConfig', 
               'Remove-AzApplicationGatewayRedirectConfiguration', 
               'Remove-AzApplicationGatewayRequestRoutingRule', 
               'Remove-AzApplicationGatewayRewriteRuleSet', 
               'Remove-AzApplicationGatewayRoutingRule', 
               'Remove-AzApplicationGatewaySslCertificate', 
               'Remove-AzApplicationGatewaySslPolicy', 
               'Remove-AzApplicationGatewaySslProfile', 
               'Remove-AzApplicationGatewaySslProfilePolicy', 
               'Remove-AzApplicationGatewayTrustedClientCertificate', 
               'Remove-AzApplicationGatewayTrustedRootCertificate', 
               'Remove-AzApplicationGatewayUrlPathMapConfig', 
               'Remove-AzApplicationSecurityGroup', 'Remove-AzBastion', 
               'Remove-AzBastionShareableLink', 'Remove-AzCustomIpPrefix', 
               'Remove-AzDdosProtectionPlan', 'Remove-AzDelegation', 
               'Remove-AzExpressRouteCircuit', 
               'Remove-AzExpressRouteCircuitAuthorization', 
               'Remove-AzExpressRouteCircuitConnectionConfig', 
               'Remove-AzExpressRouteCircuitMicrosoftPeeringPrefixConfig', 
               'Remove-AzExpressRouteCircuitPeeringConfig', 
               'Remove-AzExpressRouteConnection', 
               'Remove-AzExpressRouteCrossConnectionPeering', 
               'Remove-AzExpressRouteGateway', 'Remove-AzExpressRoutePort', 
               'Remove-AzExpressRoutePortAuthorization', 
               'Remove-AzExpressRoutePortIdentity', 'Remove-AzFirewall', 
               'Remove-AzFirewallPolicy', 'Remove-AzFirewallPolicyDraft', 
               'Remove-AzFirewallPolicyRuleCollectionGroup', 
               'Remove-AzFirewallPolicyRuleCollectionGroupDraft', 
               'Remove-AzIpAllocation', 'Remove-AzIpGroup', 'Remove-AzLoadBalancer', 
               'Remove-AzLoadBalancerBackendAddressPool', 
               'Remove-AzLoadBalancerBackendAddressPoolConfig', 
               'Remove-AzLoadBalancerFrontendIpConfig', 
               'Remove-AzLoadBalancerInboundNatPoolConfig', 
               'Remove-AzLoadBalancerInboundNatRuleConfig', 
               'Remove-AzLoadBalancerOutboundRuleConfig', 
               'Remove-AzLoadBalancerProbeConfig', 
               'Remove-AzLoadBalancerRuleConfig', 'Remove-AzLocalNetworkGateway', 
               'Remove-AzNatGateway', 'Remove-AzNetworkInterface', 
               'Remove-AzNetworkInterfaceIpConfig', 
               'Remove-AzNetworkInterfaceTapConfig', 'Remove-AzNetworkManager', 
               'Remove-AzNetworkManagerConnectivityConfiguration', 
               'Remove-AzNetworkManagerGroup', 'Remove-AzNetworkManagerIpamPool', 
               'Remove-AzNetworkManagerIpamPoolStaticCidr', 
               'Remove-AzNetworkManagerManagementGroupConnection', 
               'Remove-AzNetworkManagerRoutingConfiguration', 
               'Remove-AzNetworkManagerRoutingRule', 
               'Remove-AzNetworkManagerRoutingRuleCollection', 
               'Remove-AzNetworkManagerScopeConnection', 
               'Remove-AzNetworkManagerSecurityAdminConfiguration', 
               'Remove-AzNetworkManagerSecurityAdminRule', 
               'Remove-AzNetworkManagerSecurityAdminRuleCollection', 
               'Remove-AzNetworkManagerSecurityUserConfiguration', 
               'Remove-AzNetworkManagerSecurityUserRule', 
               'Remove-AzNetworkManagerSecurityUserRuleCollection', 
               'Remove-AzNetworkManagerStaticMember', 
               'Remove-AzNetworkManagerSubscriptionConnection', 
               'Remove-AzNetworkManagerVerifierWorkspace', 
               'Remove-AzNetworkManagerVerifierWorkspaceReachabilityAnalysisIntent', 
               'Remove-AzNetworkManagerVerifierWorkspaceReachabilityAnalysisRun', 
               'Remove-AzNetworkProfile', 'Remove-AzNetworkSecurityGroup', 
               'Remove-AzNetworkSecurityRuleConfig', 
               'Remove-AzNetworkVirtualAppliance', 'Remove-AzNetworkWatcher', 
               'Remove-AzNetworkWatcherConnectionMonitor', 
               'Remove-AzNetworkWatcherFlowLog', 
               'Remove-AzNetworkWatcherPacketCapture', 'Remove-AzP2sVpnGateway', 
               'Remove-AzPrivateDnsZoneGroup', 'Remove-AzPrivateEndpoint', 
               'Remove-AzPrivateEndpointConnection', 'Remove-AzPrivateLinkService', 
               'Remove-AzPublicIpAddress', 'Remove-AzPublicIpPrefix', 
               'Remove-AzRouteConfig', 'Remove-AzRouteFilter', 
               'Remove-AzRouteFilterRuleConfig', 'Remove-AzRouteMap', 
               'Remove-AzRouteServer', 'Remove-AzRouteServerPeer', 
               'Remove-AzRouteTable', 'Remove-AzRoutingIntent', 
               'Remove-AzRoutingPolicy', 'Remove-AzSecurityPartnerProvider', 
               'Remove-AzServiceEndpointPolicy', 
               'Remove-AzServiceEndpointPolicyDefinition', 
               'Remove-AzVHubRouteTable', 'Remove-AzVirtualApplianceSite', 
               'Remove-AzVirtualHub', 'Remove-AzVirtualHubBgpConnection', 
               'Remove-AzVirtualHubRouteTable', 
               'Remove-AzVirtualHubVnetConnection', 'Remove-AzVirtualNetwork', 
               'Remove-AzVirtualNetworkGateway', 
               'Remove-AzVirtualNetworkGatewayConnection', 
               'Remove-AzVirtualNetworkGatewayDefaultSite', 
               'Remove-AzVirtualNetworkGatewayIpConfig', 
               'Remove-AzVirtualNetworkGatewayNatRule', 
               'Remove-AzVirtualNetworkPeering', 
               'Remove-AzVirtualNetworkSubnetConfig', 'Remove-AzVirtualNetworkTap', 
               'Remove-AzVirtualRouter', 'Remove-AzVirtualRouterPeer', 
               'Remove-AzVirtualWan', 'Remove-AzVpnClientIpsecParameter', 
               'Remove-AzVpnClientRevokedCertificate', 
               'Remove-AzVpnClientRootCertificate', 'Remove-AzVpnConnection', 
               'Remove-AzVpnGateway', 'Remove-AzVpnGatewayNatRule', 
               'Remove-AzVpnServerConfiguration', 
               'Remove-AzVpnServerConfigurationPolicyGroup', 'Remove-AzVpnSite', 
               'Reset-AzHubRouter', 'Reset-AzP2sVpnGateway', 
               'Reset-AzVirtualNetworkGateway', 
               'Reset-AzVirtualNetworkGatewayConnection', 
               'Reset-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Reset-AzVpnGateway', 'Reset-AzVpnSiteLinkConnection', 
               'Resize-AzVirtualNetworkGateway', 
               'Restart-AzNetworkVirtualAppliance', 'Set-AzApplicationGateway', 
               'Set-AzApplicationGatewayAuthenticationCertificate', 
               'Set-AzApplicationGatewayAutoscaleConfiguration', 
               'Set-AzApplicationGatewayBackendAddressPool', 
               'Set-AzApplicationGatewayBackendHttpSetting', 
               'Set-AzApplicationGatewayBackendSetting', 
               'Set-AzApplicationGatewayClientAuthConfiguration', 
               'Set-AzApplicationGatewayConnectionDraining', 
               'Set-AzApplicationGatewayCustomError', 
               'Set-AzApplicationGatewayFirewallPolicy', 
               'Set-AzApplicationGatewayFrontendIPConfig', 
               'Set-AzApplicationGatewayFrontendPort', 
               'Set-AzApplicationGatewayHttpListener', 
               'Set-AzApplicationGatewayHttpListenerCustomError', 
               'Set-AzApplicationGatewayIdentity', 
               'Set-AzApplicationGatewayIPConfiguration', 
               'Set-AzApplicationGatewayListener', 
               'Set-AzApplicationGatewayPrivateLinkConfiguration', 
               'Set-AzApplicationGatewayProbeConfig', 
               'Set-AzApplicationGatewayRedirectConfiguration', 
               'Set-AzApplicationGatewayRequestRoutingRule', 
               'Set-AzApplicationGatewayRewriteRuleSet', 
               'Set-AzApplicationGatewayRoutingRule', 
               'Set-AzApplicationGatewaySku', 
               'Set-AzApplicationGatewaySslCertificate', 
               'Set-AzApplicationGatewaySslPolicy', 
               'Set-AzApplicationGatewaySslProfile', 
               'Set-AzApplicationGatewaySslProfilePolicy', 
               'Set-AzApplicationGatewayTrustedClientCertificate', 
               'Set-AzApplicationGatewayTrustedRootCertificate', 
               'Set-AzApplicationGatewayUrlPathMapConfig', 
               'Set-AzApplicationGatewayWebApplicationFirewallConfiguration', 
               'Set-AzBastion', 'Set-AzExpressRouteCircuit', 
               'Set-AzExpressRouteCircuitConnectionConfig', 
               'Set-AzExpressRouteCircuitMicrosoftPeeringPrefixConfig', 
               'Set-AzExpressRouteCircuitPeeringConfig', 
               'Set-AzExpressRouteConnection', 'Set-AzExpressRouteCrossConnection', 
               'Set-AzExpressRouteGateway', 'Set-AzExpressRoutePort', 
               'Set-AzExpressRoutePortIdentity', 'Set-AzFirewall', 
               'Set-AzFirewallPolicy', 'Set-AzFirewallPolicyDraft', 
               'Set-AzFirewallPolicyRuleCollectionGroup', 
               'Set-AzFirewallPolicyRuleCollectionGroupDraft', 
               'Set-AzIpAllocation', 'Set-AzIpGroup', 'Set-AzLoadBalancer', 
               'Set-AzLoadBalancerBackendAddressPool', 
               'Set-AzLoadBalancerFrontendIpConfig', 
               'Set-AzLoadBalancerInboundNatPoolConfig', 
               'Set-AzLoadBalancerInboundNatRuleConfig', 
               'Set-AzLoadBalancerOutboundRuleConfig', 
               'Set-AzLoadBalancerProbeConfig', 'Set-AzLoadBalancerRuleConfig', 
               'Set-AzLocalNetworkGateway', 'Set-AzNatGateway', 
               'Set-AzNetworkInterface', 'Set-AzNetworkInterfaceIpConfig', 
               'Set-AzNetworkInterfaceTapConfig', 'Set-AzNetworkManager', 
               'Set-AzNetworkManagerConnectivityConfiguration', 
               'Set-AzNetworkManagerGroup', 'Set-AzNetworkManagerIpamPool', 
               'Set-AzNetworkManagerManagementGroupConnection', 
               'Set-AzNetworkManagerRoutingConfiguration', 
               'Set-AzNetworkManagerRoutingRule', 
               'Set-AzNetworkManagerRoutingRuleCollection', 
               'Set-AzNetworkManagerScopeConnection', 
               'Set-AzNetworkManagerSecurityAdminConfiguration', 
               'Set-AzNetworkManagerSecurityAdminRule', 
               'Set-AzNetworkManagerSecurityAdminRuleCollection', 
               'Set-AzNetworkManagerSecurityUserConfiguration', 
               'Set-AzNetworkManagerSecurityUserRule', 
               'Set-AzNetworkManagerSecurityUserRuleCollection', 
               'Set-AzNetworkManagerSubscriptionConnection', 
               'Set-AzNetworkManagerVerifierWorkspace', 'Set-AzNetworkProfile', 
               'Set-AzNetworkSecurityGroup', 'Set-AzNetworkSecurityRuleConfig', 
               'Set-AzNetworkWatcherConfigFlowLog', 
               'Set-AzNetworkWatcherConnectionMonitor', 
               'Set-AzNetworkWatcherFlowLog', 'Set-AzPrivateDnsZoneGroup', 
               'Set-AzPrivateEndpoint', 'Set-AzPrivateEndpointConnection', 
               'Set-AzPrivateLinkService', 'Set-AzPublicIpAddress', 
               'Set-AzPublicIpPrefix', 'Set-AzRouteConfig', 'Set-AzRouteFilter', 
               'Set-AzRouteFilterRuleConfig', 'Set-AzRouteTable', 
               'Set-AzRoutingIntent', 'Set-AzRoutingPolicy', 
               'Set-AzSecurityPartnerProvider', 'Set-AzServiceEndpointPolicy', 
               'Set-AzServiceEndpointPolicyDefinition', 'Set-AzVirtualHub', 
               'Set-AzVirtualNetwork', 'Set-AzVirtualNetworkGateway', 
               'Set-AzVirtualNetworkGatewayConnection', 
               'Set-AzVirtualNetworkGatewayConnectionSharedKey', 
               'Set-AzVirtualNetworkGatewayDefaultSite', 
               'Set-AzVirtualNetworkPeering', 'Set-AzVirtualNetworkSubnetConfig', 
               'Set-AzVirtualNetworkTap', 'Set-AzVpnClientIpsecParameter', 
               'Start-AzApplicationGateway', 
               'Start-AzNetworkWatcherResourceTroubleshooting', 
               'Start-AzVirtualNetworkGatewayConnectionPacketCapture', 
               'Start-AzVirtualnetworkGatewayPacketCapture', 
               'Start-AzVpnConnectionPacketCapture', 
               'Start-AzVpnGatewayPacketCapture', 'Stop-AzApplicationGateway', 
               'Stop-AzNetworkWatcherConnectionMonitor', 
               'Stop-AzNetworkWatcherPacketCapture', 
               'Stop-AzVirtualNetworkGatewayConnectionPacketCapture', 
               'Stop-AzVirtualNetworkGatewayPacketCapture', 
               'Stop-AzVpnConnectionPacketCapture', 
               'Stop-AzVpnGatewayPacketCapture', 'Sync-AzVirtualNetworkPeering', 
               'Test-AzDnsAvailability', 'Test-AzNetworkWatcherConnectivity', 
               'Test-AzNetworkWatcherIPFlow', 
               'Test-AzPrivateIPAddressAvailability', 
               'Test-AzPrivateLinkServiceVisibility', 'Update-AzCustomIpPrefix', 
               'Update-AzNetworkVirtualAppliance', 
               'Update-AzNetworkVirtualApplianceConnection', 
               'Update-AzP2sVpnGateway', 'Update-AzRouteMap', 'Update-AzRouteServer', 
               'Update-AzRouteServerPeer', 'Update-AzVHubRouteTable', 
               'Update-AzVirtualApplianceInboundSecurityRule', 
               'Update-AzVirtualApplianceSite', 'Update-AzVirtualHub', 
               'Update-AzVirtualHubBgpConnection', 
               'Update-AzVirtualHubVnetConnection', 
               'Update-AzVirtualNetworkGatewayNatRule', 'Update-AzVirtualRouter', 
               'Update-AzVirtualRouterPeer', 'Update-AzVirtualWan', 
               'Update-AzVpnConnection', 'Update-AzVpnGateway', 
               'Update-AzVpnGatewayNatRule', 'Update-AzVpnServerConfiguration', 
               'Update-AzVpnServerConfigurationPolicyGroup', 'Update-AzVpnSite'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Add-AzApplicationGatewayBackendHttpSettings', 
               'Get-AzApplicationGatewayAvailableSslOptions', 
               'Get-AzApplicationGatewayAvailableWafRuleSets', 
               'Get-AzApplicationGatewayBackendHttpSettings', 
               'Get-AzExpressRouteCircuitStats', 'Get-AzInterfaceEndpoint', 
               'List-AzApplicationGatewayAvailableServerVariableAndHeader', 
               'List-AzApplicationGatewayAvailableSslOptions', 
               'List-AzApplicationGatewayAvailableWafRuleSets', 
               'List-AzApplicationGatewaySslPredefinedPolicy', 
               'New-AzApplicationGatewayBackendHttpSettings', 
               'New-AzFirewallThreatIntelWhitelistObject', 
               'Remove-AzApplicationGatewayBackendHttpSettings', 
               'Set-AzApplicationGatewayBackendHttpSettings'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '5.2.0'; })

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','Network','VirtualNetwork'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Returned appgw and agc in waf policy
* Updated cmdlet ''New-AzFirewallPolicyApplicationRule'' to use HTTPS as the default protocol when creating a new FQDN Tag application rule.
* Added ''EnableDnstapLogging'' parameter to ''New-AzFirewall'''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoVQYJKoZIhvcNAQcCoIIoRjCCKEICAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCBZXv0hNP2XUiWU
# 9eMUGQfPT2GrWlMvi/1AsIyOBp+Q2KCCDYUwggYDMIID66ADAgECAhMzAAAEhJji
# EuB4ozFdAAAAAASEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjUwNjE5MTgyMTM1WhcNMjYwNjE3MTgyMTM1WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQDtekqMKDnzfsyc1T1QpHfFtr+rkir8ldzLPKmMXbRDouVXAsvBfd6E82tPj4Yz
# aSluGDQoX3NpMKooKeVFjjNRq37yyT/h1QTLMB8dpmsZ/70UM+U/sYxvt1PWWxLj
# MNIXqzB8PjG6i7H2YFgk4YOhfGSekvnzW13dLAtfjD0wiwREPvCNlilRz7XoFde5
# KO01eFiWeteh48qUOqUaAkIznC4XB3sFd1LWUmupXHK05QfJSmnei9qZJBYTt8Zh
# ArGDh7nQn+Y1jOA3oBiCUJ4n1CMaWdDhrgdMuu026oWAbfC3prqkUn8LWp28H+2S
# LetNG5KQZZwvy3Zcn7+PQGl5AgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQUBN/0b6Fh6nMdE4FAxYG9kWCpbYUw
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwNTM2MjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AGLQps1XU4RTcoDIDLP6QG3NnRE3p/WSMp61Cs8Z+JUv3xJWGtBzYmCINmHVFv6i
# 8pYF/e79FNK6P1oKjduxqHSicBdg8Mj0k8kDFA/0eU26bPBRQUIaiWrhsDOrXWdL
# m7Zmu516oQoUWcINs4jBfjDEVV4bmgQYfe+4/MUJwQJ9h6mfE+kcCP4HlP4ChIQB
# UHoSymakcTBvZw+Qst7sbdt5KnQKkSEN01CzPG1awClCI6zLKf/vKIwnqHw/+Wvc
# Ar7gwKlWNmLwTNi807r9rWsXQep1Q8YMkIuGmZ0a1qCd3GuOkSRznz2/0ojeZVYh
# ZyohCQi1Bs+xfRkv/fy0HfV3mNyO22dFUvHzBZgqE5FbGjmUnrSr1x8lCrK+s4A+
# bOGp2IejOphWoZEPGOco/HEznZ5Lk6w6W+E2Jy3PHoFE0Y8TtkSE4/80Y2lBJhLj
# 27d8ueJ8IdQhSpL/WzTjjnuYH7Dx5o9pWdIGSaFNYuSqOYxrVW7N4AEQVRDZeqDc
# fqPG3O6r5SNsxXbd71DCIQURtUKss53ON+vrlV0rjiKBIdwvMNLQ9zK0jy77owDy
# XXoYkQxakN2uFIBO1UNAvCYXjs4rw3SRmBX9qiZ5ENxcn/pLMkiyb68QdwHUXz+1
# fI6ea3/jjpNPz6Dlc/RMcXIWeMMkhup/XEbwu73U+uz/MIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGiYwghoiAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAASEmOIS4HijMV0AAAAA
# BIQwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIBJy
# ymbY57eJVvkeqW4T21LU0GJj2TzF+YvH0ePOhKjOMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAInHgI9gXXHh5DZHdETh4rRN9dLV+ZRCPDUb+
# EDD4quPPQFr+uFGnHJcpVFnBMuQULBdjbfxr7wAH+IwYjFTJUdOPAMRWsdYVSUDh
# YUknZMzeE/W031vOSAVKCrH8UF7bHlUDBJ87+hdbbFp5Lhs3vMQsrmHGMo7PxjhD
# MgtrkJfvAvgqa1yaqO36HVSovEdBNvC4/Jf1XZW7FevozP8C4OcorK9z2PCTIqp8
# ATQ4+TBHg6Buy1W36KS87qwmlcEmrwVDkSE/f6jmopPNxVyXkrHy8YV5FgesVa0+
# dfZYCAXbfn13AK1Ldqqhw60zeiL/k3BrWeqOtrVLtDFluWyeWKGCF7AwghesBgor
# BgEEAYI3AwMBMYIXnDCCF5gGCSqGSIb3DQEHAqCCF4kwgheFAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCCCHto3tat08HbMjvEQMWzrQarWQB65L5zi
# CYBs5tGDdQIGaHpZR7BiGBMyMDI1MDczMDA0MTU0Mi4wNDFaMASAAgH0oIHZpIHW
# MIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
# Hm5TaGllbGQgVFNTIEVTTjoyRDFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCEf4wggcoMIIFEKADAgECAhMzAAAB/XP5
# aFrNDGHtAAEAAAH9MA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMB4XDTI0MDcyNTE4MzExNloXDTI1MTAyMjE4MzExNlowgdMxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jv
# c29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVs
# ZCBUU1MgRVNOOjJEMUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
# ZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# oWWs+D+Ou4JjYnRHRedu0MTFYzNJEVPnILzc02R3qbnujvhZgkhp+p/lymYLzkQy
# G2zpxYceTjIF7HiQWbt6FW3ARkBrthJUz05ZnKpcF31lpUEb8gUXiD2xIpo8YM+S
# D0S+hTP1TCA/we38yZ3BEtmZtcVnaLRp/Avsqg+5KI0Kw6TDJpKwTLl0VW0/23sK
# ikeWDSnHQeTprO0zIm/btagSYm3V/8zXlfxy7s/EVFdSglHGsUq8EZupUO8XbHzz
# 7tURyiD3kOxNnw5ox1eZX/c/XmW4H6b4yNmZF0wTZuw37yA1PJKOySSrXrWEh+H6
# ++Wb6+1ltMCPoMJHUtPP3Cn0CNcNvrPyJtDacqjnITrLzrsHdOLqjsH229Zkvndk
# 0IqxBDZgMoY+Ef7ffFRP2pPkrF1F9IcBkYz8hL+QjX+u4y4Uqq4UtT7VRnsqvR/x
# /+QLE0pcSEh/XE1w1fcp6Jmq8RnHEXikycMLN/a/KYxpSP3FfFbLZuf+qIryFL0g
# EDytapGn1ONjVkiKpVP2uqVIYj4ViCjy5pLUceMeqiKgYqhpmUHCE2WssLLhdQBH
# dpl28+k+ZY6m4dPFnEoGcJHuMcIZnw4cOwixojROr+Nq71cJj7Q4L0XwPvuTHQt0
# oH7RKMQgmsy7CVD7v55dOhdHXdYsyO69dAdK+nWlyYcCAwEAAaOCAUkwggFFMB0G
# A1UdDgQWBBTpDMXA4ZW8+yL2+3vA6RmU7oEKpDAfBgNVHSMEGDAWgBSfpxVdAF5i
# XYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
# c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
# JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRp
# bWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1Ud
# JQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
# AAOCAgEAY9hYX+T5AmCrYGaH96TdR5T52/PNOG7ySYeopv4flnDWQLhBlravAg+p
# jlNv5XSXZrKGv8e4s5dJ5WdhfC9ywFQq4TmXnUevPXtlubZk+02BXK6/23hM0TSK
# s2KlhYiqzbRe8QbMfKXEDtvMoHSZT7r+wI2IgjYQwka+3P9VXgERwu46/czz8IR/
# Zq+vO5523Jld6ssVuzs9uwIrJhfcYBj50mXWRBcMhzajLjWDgcih0DuykPcBpoTL
# lOL8LpXooqnr+QLYE4BpUep3JySMYfPz2hfOL3g02WEfsOxp8ANbcdiqM31dm3vS
# heEkmjHA2zuM+Tgn4j5n+Any7IODYQkIrNVhLdML09eu1dIPhp24lFtnWTYNaFTO
# fMqFa3Ab8KDKicmp0AthRNZVg0BPAL58+B0UcoBGKzS9jscwOTu1JmNlisOKkVUV
# kSJ5Fo/ctfDSPdCTVaIXXF7l40k1cM/X2O0JdAS97T78lYjtw/PybuzX5shxBh/R
# qTPvCyAhIxBVKfN/hfs4CIoFaqWJ0r/8SB1CGsyyIcPfEgMo8ceq1w5Zo0JfnyFi
# 6Guo+z3LPFl/exQaRubErsAUTfyBY5/5liyvjAgyDYnEB8vHO7c7Fg2tGd5hGgYs
# +AOoWx24+XcyxpUkAajDhky9Dl+8JZTjts6BcT9sYTmOodk/SgIwggdxMIIFWaAD
# AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3Nv
# ZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIy
# MjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5
# vQ7VgtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64
# NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhu
# je3XD9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
# 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPg
# yY9+tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I
# 5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2
# ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/
# TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy
# 16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
# 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
# XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMB
# AAEwIwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQW
# BBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30B
# ATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYB
# BAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMB
# Af8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBL
# oEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
# TWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggr
# BgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
# reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27
# DzHkwo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pv
# vinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9Ak
# vUCgvxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
# NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2
# kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+
# c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep
# 8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+Dvk
# txW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1Zyvg
# DbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
# 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDWTCCAkECAQEwggEBoYHZpIHW
# MIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
# Hm5TaGllbGQgVFNTIEVTTjoyRDFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUAoj0WtVVQUNSK
# oqtrjinRAsBUdoOggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDANBgkqhkiG9w0BAQsFAAIFAOw0ADgwIhgPMjAyNTA3MzAwMjIxNDRaGA8yMDI1
# MDczMTAyMjE0NFowdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA7DQAOAIBADAKAgEA
# AgIS6gIB/zAHAgEAAgIS/DAKAgUA7DVRuAIBADA2BgorBgEEAYRZCgQCMSgwJjAM
# BgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEB
# CwUAA4IBAQAnjoJJEtKK6L2dtBGgcvzVPksFVo7KdkxxwesbOgMCk9yCmrNBZoNl
# vNmAs/uEBk7EFWoaYRnYTcfU39IijHQ/DJ3qlWqeR7xvIdhJqyUzYYKqLoOPSwuC
# Kp2WI7dv/WC7aZToegYo5MRclzCy1MiK4hjBwwGho7hYJd9VONTn+WHwGSUBIGsZ
# jXohdq89iW76yZbHEA7Ek6QGqs5xEv5bJVEfioatmefJQfLJZEd/7Hsg7ECUV8hD
# qgcYTH0rX+Pgd5HirjMdIMKGrZsWU51G6ZRKvNg1BGEde3KhUMKuHynoMAe4QnPU
# 1IpXLatRpfId7TstPbwJTfk8I5gvKn9xMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UE
# BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
# BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAH9c/loWs0MYe0AAQAAAf0wDQYJYIZI
# AWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG
# 9w0BCQQxIgQgM+dz7KCiWLROomttTIm5e5cRUa7LjnwhUVB3Kb8+1OkwgfoGCyqG
# SIb3DQEJEAIvMYHqMIHnMIHkMIG9BCCAKEgNyUowvIfx/eDfYSupHkeF1p6GFwjK
# Bs8lRB4NRzCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMz
# AAAB/XP5aFrNDGHtAAEAAAH9MCIEIPdA3kiNZrwMel7eOKFPP0DI2ymCaThs864l
# JWXJ4RGEMA0GCSqGSIb3DQEBCwUABIICAJCAgQcT94idFMtX2Mz5y1T9Dw9+H3y2
# yW0x3mqrXP1/SuR1zmjoz7EtVwjaplbvwuIUZO6ToaPe9it6Z3XNAM32W0Pf39bs
# IOL+ks9Dh1wd/V5jBbkEHtVvM8gnT7YZfW6sZ6MdevYWeDRcW39S8QYxCOtDR0CW
# BoyVXp9K/z96ugjEvOWc/lD/n0e4g2/gw0UHOvBr1Vn7+HIXfUk6CbrepqIZlIMR
# cHLuwZz7g9bGv51tYq839d1PSlR4JY/yHMvtxVVPDND4TxXb5PH06lTBPGl+6zaT
# PKqb1ii8g4G4U/T7+VXkTlHm5/FUe+f4I6n1b1Eto3BzBm48LmwzI27omgu6cyxB
# Qx9uD2sOMVWu1LT4ui1L/P/n9gIazVzZhHYfIIRKJ+D53IuDafSwz+XdjZHsoxwj
# CVzJhHUFb8jXOJQKNeaz+ZUAvh6KwuWNZfDkN+dRv43WEelOz0U9xIZ8jgI4Hcpl
# 0/YPCwB3iiNDin9kjczRH7cYw4jualv6uErrwjYkPLIJNy+p25a7c0W7Am+l8JB3
# lTl58MWmV2e9tKijtnx5VZUUTjx/dM1/EvNrVFvFLQZIXX4N2gKQCQc2Ve5QUaRp
# s/lX9VplZ+SSAl4Wamzg3qOIVyWjfYM+tR4j2oRjnMgV7xR8o+YHXSLOZaxBqhV6
# 9wnSSiak/Gu8
# SIG # End signature block
