trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform-codes'
        backendServiceArm: 'Free Trial(08fcb844-e578-44ed-adfb-519383394cb0)'
        backendAzureRmResourceGroupName: 'DevOps'
        backendAzureRmStorageAccountName: 'store123devops'
        backendAzureRmContainerName: 'devops'
        backendAzureRmKey: 'devops.tfstate'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform-codes'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform-codes'
        environmentServiceNameAzureRM: 'Free Trial(08fcb844-e578-44ed-adfb-519383394cb0)'
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform-codes'
        environmentServiceNameAzureRM: 'Free Trial(08fcb844-e578-44ed-adfb-519383394cb0)'

